name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 0 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.GH_TOKEN }}

          # Options
          user: FlyingV111
          template: classic
          base: header, activity, repositories
          config_timezone: Europe/Berlin

          # Language Icons
          plugin_topics: yes
          plugin_topics_mode: 'icons'
          plugin_topics_sort: 'activity'
          plugin_topics_limit: 12

          # Introduction
          plugin_introduction: yes
          plugin_introduction_title: yes

          # IsoCalendar
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          # Lines
          plugin_lines: yes
